[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs", "postgresql"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader --no-interaction"
]

[phases.build]
cmds = [
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"

[variables]
NIXPACKS_PHP_ROOT_DIR = "/app"
NIXPACKS_PHP_FALLBACK_PATH = "/app/public/index.php" 